virtualbox:
  name: 'PepysDiary'
  memory: '512'
django:
  settings_module: pepysdiary.settings.vagrant
virtualenv:
  envname: pepysdiary
foreman:
  procfile: Procfile.dev
db:
  name: pepysdiary
  user: pepysdiary
  password: pepysdiary
use_geodjango: 'false'

